### ISSUE TITLE
add last fully covered version to readme

### ISSUE THREAD

**Issue by matkoniecz** [goldfndr/StreetCompleteJSON#11]
it would make easier to update missing data

**Comment by rugk** [comment]
You can see that in the git commits…

Maybe rather something like "all changes since verdion X.Y of StreetComplete included".

**Comment by matkoniecz** [comment]
Yes, I meant date of StreetComplete that is fully covered. Using version numbers is probably better.

**Comment by goldfndr** [comment]
It looks like there were no tagging changes between v8.0 and v8.1. Is that correct?

**Comment by matkoniecz** [comment]
It seems so.

**Comment by westnordost** [comment]
Yes 

Am 30. September 2018 02:29:22 MESZ schrieb Richard Finegold <notifications@github.com>:
>It looks like there were no tagging changes between v8.0 and v8.1. Is
>that correct?

**Comment by goldfndr** [comment]
I'm thinking it's going to be much simpler to document the change in the commit message rather than each time opening another file, editing a single line in it, and saving the file.  Additionally, many tag changes to the app don't spawn releases, and there's one release now that didn't include any changes to the tags.
