### ISSUE TITLE
You consider including images of the quests?

### ISSUE THREAD

**Issue by rugk** [goldfndr/StreetCompleteJSON#5]
In such a case you can use [this repo](https://github.com/rugk/streetcomplete-quest-svgs), as a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules). The file names are the original ones as in StreetComplete.

But generally I also wonder where on taginfo this might be shown, is not only the icon of the application shown?

**Comment by goldfndr** [comment]
Sure, I can use those instead of the OSM wiki's copies. However, what would be easier on me, rather than messing with a submodule and having to fetch+commit changes (which appears to require the command line), is if you enable GitHub Pages on your repo: Repo settings, scroll down to GitHub Pages, change Source to master branch.

Then, I'll be able to directly use http://rugk.github.io/streetcomplete-quest-svgs/optimized/ic_quest_traffic_lights.svg and so on. Without that, it's not easy to get the proper MIME type. (raw becomes text/plain.) Believe it or not, I haven't cloned this repository locally, all my transactions so far have been through the web pages. I'll eventually clone it, but no need yet.

If you look at the tags of [historic.place](https://taginfo.openstreetmap.org/projects/historic_place#tags) or any of the [Traffic Signs](https://taginfo.openstreetmap.org/projects/traffic_signs_ame#tags) or a few others (e.g. JOSM, OsmAnd), you'll see that the Description starts with an image if an image is set. I was a bit surprised to discover that the images weren't originally 16x16, the web pages uses `<img src="..." alt="" style="max-width: 16px; max-height: 16px;">`. So I like the idea of using SVGs: on so-called retina displays the 16px image should be more detailed.

It looks like you aren't hosting the StreetComplete logo, but that is admittedly outside your repo's scope.

**Comment by rugk** [comment]
Ah, great. It looks as if you are looking for https://rawgit.com/. Input any GitHub(raw) URL and it serves it with the correct mime type. So I don't need to enable GitHub Pages. 😄 

But, BTW:
> Sure, I can use those instead of the OSM wiki's copies. 

These are the same. Just the file names are different.

**Comment by goldfndr** [comment]
taginfo is already using deep-linked images from the OSM wiki, so it obviously already has permission to do so. See [highway=service](https://taginfo.openstreetmap.org/tags/highway=service) for example, which is using [the wiki image](https://wiki.openstreetmap.org/w/images/thumb/e/ed/Geograph-3398520-by-Russel-Wills.jpg/300px-Geograph-3398520-by-Russel-Wills.jpg). So I see no compelling reason to change the image URLs, other than maybe shortening the URL and/or changing whose bandwidth is used.

Note to self: I'd change the URLs based on [this commit](https://github.com/rugk/streetcomplete-quest-svgs/commit/79e46ef1621147b42659d8708bd4156c6f636a49) rather than having to go through [each quest's](https://github.com/westnordost/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests) java file looking for the `getIcon` function.

I spot-checked the image updating on the OSM wiki via https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_notes.svg and observed that the https://wiki.openstreetmap.org/w/images/f/f1/StreetComplete_quest_notes.svg location doesn't vary with revisions. I did not check what the effect would be if the image was renamed (wiki page moved).

https://rawgit.com/ is a third-party service.

**Comment by goldfndr** [comment]
Out of curiosity, why are you against enabling GitHub Pages on your repository?

**Comment by westnordost** [comment]
By the way, did you read this?
https://github.com/westnordost/StreetComplete/issues/864#issuecomment-366328440

I think it is a good idea to simply use the pictures from the wiki (scaled to the correct size) - it is closer to OSM infrastructure.

**Comment by rugk** [comment]
> Out of curiosity, why are you against enabling GitHub Pages on your repository?

Nothing special, when it is not necessary I'd just avoid it, as that thing is not a website. And, as said, you have another way that works.

**Comment by rugk** [comment]
So current status is that the wiki is used. I guess this is totally fine. :smiley:

**Comment by goldfndr** [comment]
[RawGit](https://rawgit.com/) has announced that it will be shutting down.
